-- =============================================================================
-- Seed Data for ClubhouseUpdate
-- Run with: supabase db reset
-- All slugger_user_id values prefixed "dev-" for dev mode compatibility.
-- CURRENT_DATE is used so team 1 always has a home game today.
-- =============================================================================

-- ── Teams ────────────────────────────────────────────────────────────────────
INSERT INTO teams (team_name) VALUES
  ('Long Island Ducks'),       -- id 1
  ('Lancaster Stormers'),      -- id 2
  ('York Revolution'),         -- id 3
  ('Southern Maryland Blue Crabs'); -- id 4

-- ── Users ────────────────────────────────────────────────────────────────────
-- Team 1 (Long Island Ducks): CM (onboarding done), CM (not done), GM, 3 players
-- Team 2 (Lancaster Stormers): CM, GM, 2 players
-- Teams 3/4: sparse

INSERT INTO users (slugger_user_id, user_name, email, role, team_id, has_completed_onboarding) VALUES
  -- Long Island Ducks
  ('dev-cm-1',   'Casey Morgan',     'cm1@dev.test',    'clubhouse_manager', 1, true),
  ('dev-cm-2',   'Drew Rivera',      'cm2@dev.test',    'clubhouse_manager', 1, false), -- onboarding gate test
  ('dev-gm-1',   'Taylor Brooks',    'gm1@dev.test',    'general_manager',   1, true),
  ('dev-p-1',    'Jordan Lee',       'p1@dev.test',     'player',            1, true),
  ('dev-p-2',    'Marcus Webb',      'p2@dev.test',     'player',            1, true),
  ('dev-p-3',    'Carlos Reyes',     'p3@dev.test',     'player',            1, true),

  -- Lancaster Stormers
  ('dev-cm-3',   'Sam Nguyen',       'cm3@dev.test',    'clubhouse_manager', 2, true),
  ('dev-gm-2',   'Alex Kim',         'gm2@dev.test',    'general_manager',   2, true),
  ('dev-p-4',    'Tyler Moss',       'p4@dev.test',     'player',            2, true),
  ('dev-p-5',    'Dante Fuller',     'p5@dev.test',     'player',            2, true),

  -- York Revolution
  ('dev-cm-4',   'Morgan Hayes',     'cm4@dev.test',    'clubhouse_manager', 3, true),
  ('dev-gm-3',   'Chris Patel',      'gm3@dev.test',    'general_manager',   3, true),

  -- Southern Maryland Blue Crabs
  ('dev-cm-5',   'Jamie Scott',      'cm5@dev.test',    'clubhouse_manager', 4, true),
  ('dev-gm-4',   'Robin Walsh',      'gm4@dev.test',    'general_manager',   4, true),

  -- Env-var defaults: matches IDs generated by buildDevMockPayload()
  -- NEXT_PUBLIC_DEV_USER_ROLE=league  → dev-league-1
  -- NEXT_PUBLIC_DEV_USER_ROLE=gm      → dev-gm-1 (already seeded above)
  -- NEXT_PUBLIC_DEV_USER_ROLE=player  → dev-player-1
  ('dev-league-1',  'Dev CM',        'dev-league@dev.test',  'clubhouse_manager', 1, true),
  ('dev-player-1',  'Dev Player',    'dev-player@dev.test',  'player',            1, true);

-- ── Games ────────────────────────────────────────────────────────────────────
-- Series are typically 6 games (Tue–Sun or similar).
-- Team 1 (Long Island Ducks) hosts today. Off day between series.

INSERT INTO games (home_team_id, away_team_id, game_date, game_time, is_makeup) VALUES
  -- === Team 1 home series (vs Lancaster, 6 games starting today) ===
  -- Today is a game day for team 1
  (1, 2, CURRENT_DATE,       '18:35', false),
  (1, 2, CURRENT_DATE + 1,   '18:35', false),
  (1, 2, CURRENT_DATE + 2,   '18:35', false),
  (1, 2, CURRENT_DATE + 3,   '18:35', false),
  (1, 2, CURRENT_DATE + 4,   '18:35', false),
  (1, 2, CURRENT_DATE + 5,   '13:05', false),

  -- Off day: CURRENT_DATE + 6

  -- === Team 1 away series (at York, 6 games) ===
  (3, 1, CURRENT_DATE + 7,   '19:05', false),
  (3, 1, CURRENT_DATE + 8,   '19:05', false),
  (3, 1, CURRENT_DATE + 9,   '19:05', false),
  (3, 1, CURRENT_DATE + 10,  '19:05', false),
  (3, 1, CURRENT_DATE + 11,  '19:05', false),
  (3, 1, CURRENT_DATE + 12,  '13:05', false),

  -- Off day: CURRENT_DATE + 13

  -- === Team 1 home series (vs SoMD, 6 games) ===
  (1, 4, CURRENT_DATE + 14,  '18:35', false),
  (1, 4, CURRENT_DATE + 15,  '18:35', false),
  (1, 4, CURRENT_DATE + 16,  '18:35', false),
  (1, 4, CURRENT_DATE + 17,  '18:35', false),
  (1, 4, CURRENT_DATE + 18,  '18:35', false),
  (1, 4, CURRENT_DATE + 19,  '13:05', false),

  -- Makeup game (rescheduled) ===
  (1, 4, CURRENT_DATE + 20,  '18:35', true),

  -- === Team 2 (Lancaster) away series at York (same dates as team 1's away) ===
  (2, 3, CURRENT_DATE,       '19:05', false),
  (2, 3, CURRENT_DATE + 1,   '19:05', false),
  (2, 3, CURRENT_DATE + 2,   '19:05', false),
  (2, 3, CURRENT_DATE + 3,   '19:05', false),
  (2, 3, CURRENT_DATE + 4,   '19:05', false),
  (2, 3, CURRENT_DATE + 5,   '13:05', false),

  -- === Prior series (for calendar context) ===
  (1, 3, CURRENT_DATE - 7,   '18:35', false),
  (1, 3, CURRENT_DATE - 6,   '18:35', false),
  (1, 3, CURRENT_DATE - 5,   '18:35', false),
  (1, 3, CURRENT_DATE - 4,   '18:35', false),
  (1, 3, CURRENT_DATE - 3,   '18:35', false),
  (1, 3, CURRENT_DATE - 2,   '13:05', false);

-- ── Recurring Tasks (CM-1: Casey Morgan, team 1) ─────────────────────────────
INSERT INTO recurring_tasks (user_id, title, description, default_time, category, visibility, game_day_period, is_enabled)
SELECT
  user_id,
  title, description, default_time::time, category::task_category,
  visibility::task_visibility, game_day_period::game_day_period, is_enabled
FROM (VALUES
  -- Always-on tasks
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Laundry — Morning load',       'Collect and start first laundry load', '07:00', 'laundry',   'all',      null,        true),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Laundry — Afternoon load',     'Second load if needed',                '13:00', 'laundry',   'all',      null,        true),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Clubhouse clean sweep',        'Quick sweep and wipe of surfaces',     '08:00', 'sanitation','all',      null,        true),

  -- Game-day specific
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Pre-game snack setup',         'Lay out pre-game snacks',              '14:30', 'food',      'game_day', 'pre_game',  true),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Post-game meal setup',         'Heat and serve post-game meal',        '21:00', 'food',      'game_day', 'post_game', true),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Equipment check',              'Inspect and prepare equipment',        '13:00', 'equipment', 'game_day', 'pre_game',  true),

  -- Off-day task
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Deep clean locker room',       'Full disinfect and restock',           '10:00', 'sanitation','off_day',  null,        true)
) AS t(user_id, title, description, default_time, category, visibility, game_day_period, is_enabled);

-- ── Recurring Task Completions (some done, some not, for today) ───────────────
INSERT INTO recurring_task_completions (recurring_task_id, completion_date, is_complete, completed_at)
SELECT
  rt.id,
  CURRENT_DATE,
  true,
  now() - interval '2 hours'
FROM recurring_tasks rt
JOIN users u ON rt.user_id = u.id
WHERE u.slugger_user_id = 'dev-cm-1'
  AND rt.title IN ('Laundry — Morning load', 'Clubhouse clean sweep');

-- ── One-off Tasks (CM-1, scattered around this week) ─────────────────────────
INSERT INTO tasks (user_id, title, description, task_date, task_time, category, visibility, is_complete)
SELECT user_id, title, description, task_date::date, task_time::time, category::task_category, visibility::task_visibility, is_complete
FROM (VALUES
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Order batting gloves',     'Need 12 pairs size M', CURRENT_DATE,      '10:00', 'equipment', 'all', false),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Check medical supplies',   'Restock ice bags',     CURRENT_DATE + 1,  '09:00', 'medical',   'all', false),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'), 'Field inspection',         null,                   CURRENT_DATE - 1,  null,    'field',     'all', true)
) AS t(user_id, title, description, task_date, task_time, category, visibility, is_complete);

-- ── Inventory (Team 1) ───────────────────────────────────────────────────────
INSERT INTO inventory_items (team_id, item_name, category, unit, current_stock, par_level, stock_status, price_per_unit, notes)
VALUES
  -- Stocked items
  (1, 'Laundry detergent (gallon)', 'laundry_cleaning',   'gallon', 4,  2, 'stocked', 12.99, null),
  (1, 'Dryer sheets',               'laundry_cleaning',   'box',    3,  2, 'stocked',  5.49, null),
  (1, 'Disposable cups',            'food_beverage',      'sleeve', 10, 4, 'stocked',  3.99, null),
  (1, 'Athletic tape (1.5")',       'medical_safety',     'roll',   20, 8, 'stocked',  2.49, null),
  (1, 'Sunscreen SPF 50',           'hygiene_personal',   'bottle', 6,  3, 'stocked',  8.99, null),

  -- Low stock
  (1, 'Batting helmet',             'equipment_field',    'unit',   2,  6, 'low',      89.99, 'Need to order before next homestand'),
  (1, 'Ice bags (20lb)',            'medical_safety',     'bag',    1,  4, 'low',       6.99, null),

  -- Out of stock
  (1, 'Pine tar rag',               'equipment_field',    'unit',   0,  3, 'out',       4.99, 'Check with equipment manager'),
  (1, 'Gatorade powder (lemon)',    'food_beverage',      'tub',    0,  5, 'out',      14.99, 'Order asap');

-- ── Meals (linked to today''s game for Team 1) ───────────────────────────────
INSERT INTO meals (game_id, pre_game_snack, post_game_meal)
SELECT g.id, 'Peanut butter & jelly sandwiches, bananas, Gatorade', 'Chicken pasta buffet, salad, rolls'
FROM games g
WHERE g.home_team_id = 1 AND g.game_date = CURRENT_DATE
LIMIT 1;

-- ── Player Preferences (Team 1 players) ──────────────────────────────────────
INSERT INTO player_preferences (player_id, preferred_name, other_details)
VALUES
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-1'), 'J-Lee', 'Likes pasta pre-game'),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-2'), null,    null),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-3'), 'C-Rey', 'No spicy food');

INSERT INTO player_restrictions (player_id, restriction, is_custom)
VALUES
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-1'), 'Gluten-Free',     false),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-3'), 'Shellfish Allergy', false),
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-3'), 'lactose intolerant', true);

-- ── Contacts (Team 1) ────────────────────────────────────────────────────────
INSERT INTO contacts (team_id, contact_name, contact_role, phone, email, display_order, created_by)
VALUES
  (1, 'Rick White',      'Equipment Manager',  '555-0101', 'rwhite@ducks.test',  1, (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1')),
  (1, 'Linda Park',      'Team Trainer',       '555-0102', 'lpark@ducks.test',   2, (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1')),
  (1, 'Steve Groves',    'Stadium Operations', '555-0103', null,                 3, (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'));

-- ── Conversations & Messages ──────────────────────────────────────────────────
-- Direct conversation between CM-1 and GM-1
INSERT INTO conversations (id, type, name, created_by)
VALUES
  ('a0000000-0000-0000-0000-000000000001', 'direct',   null,                    (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1')),
  ('a0000000-0000-0000-0000-000000000002', 'group',    'Game Day Staff',        (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1')),
  ('a0000000-0000-0000-0000-000000000003', 'bulletin', 'League Bulletin Board', (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'));

INSERT INTO conversation_participants (conversation_id, user_id)
VALUES
  ('a0000000-0000-0000-0000-000000000001', (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1')),
  ('a0000000-0000-0000-0000-000000000001', (SELECT id FROM users WHERE slugger_user_id = 'dev-gm-1')),
  ('a0000000-0000-0000-0000-000000000002', (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1')),
  ('a0000000-0000-0000-0000-000000000002', (SELECT id FROM users WHERE slugger_user_id = 'dev-gm-1')),
  ('a0000000-0000-0000-0000-000000000002', (SELECT id FROM users WHERE slugger_user_id = 'dev-p-1')),
  ('a0000000-0000-0000-0000-000000000003', (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'));

INSERT INTO messages (id, conversation_id, sender_id, content, created_at)
VALUES
  ('b0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001',
    (SELECT id FROM users WHERE slugger_user_id = 'dev-gm-1'),
    'Hey Casey — batting helmets are getting low, can you order before the homestand?',
    now() - interval '3 hours'),
  ('b0000000-0000-0000-0000-000000000002', 'a0000000-0000-0000-0000-000000000001',
    (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'),
    'On it, just added it to the inventory list.',
    now() - interval '2 hours 50 minutes'),
  ('b0000000-0000-0000-0000-000000000003', 'a0000000-0000-0000-0000-000000000002',
    (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'),
    'Post-game meal tonight is chicken pasta. Gates open at 5pm.',
    now() - interval '1 hour');

-- ── Issues ───────────────────────────────────────────────────────────────────
INSERT INTO issues (player_id, player_team_id, team_context, away_team_name, description, status, gm_flagged, routed_to)
VALUES
  -- Resolved issue
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-1'), 1, 'home', null,
   'Shower drain in locker room is slow — standing water after games.',
   'resolved', false, 'clubhouse_manager'),

  -- Open issue
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-2'), 1, 'home', null,
   'Need extra batting gloves for BP — medium size.',
   'new', false, 'clubhouse_manager'),

  -- GM-flagged in-progress issue
  ((SELECT id FROM users WHERE slugger_user_id = 'dev-p-3'), 1, 'away', 'York Revolution',
   'Away clubhouse was out of ice for post-game — poor conditions.',
   'in_progress', true, 'clubhouse_manager');

INSERT INTO issue_comments (issue_id, user_id, comment, created_at)
VALUES
  (1, (SELECT id FROM users WHERE slugger_user_id = 'dev-cm-1'),
   'Fixed — had facilities come in this morning.', now() - interval '1 day'),
  (3, (SELECT id FROM users WHERE slugger_user_id = 'dev-gm-1'),
   'Flagging this — I''ll reach out to York''s front office.', now() - interval '2 hours');
