#!/usr/bin/env bash
# dev-setup.sh — one-command dev setup for ClubhouseUpdate
# Prerequisites: Docker Desktop running, Supabase CLI installed, Node 18+
# Usage: bash scripts/dev-setup.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

info()  { echo "  → $*"; }
ok()    { echo "  ✓ $*"; }
warn()  { echo "  ⚠ $*"; }
fatal() { echo "  ✗ $*"; exit 1; }

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Clubhouse Dev Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── 1. Install dependencies ────────────────────────────────────────────────
info "Installing npm dependencies…"
npm install --silent
ok "Dependencies installed"

# ── 2. Check Supabase CLI ─────────────────────────────────────────────────
if ! command -v supabase &>/dev/null; then
  fatal "Supabase CLI not found. Install it: https://supabase.com/docs/guides/cli/getting-started"
fi
ok "Supabase CLI found: $(supabase --version)"

# ── 3. Start Supabase (idempotent) ────────────────────────────────────────
info "Starting Supabase local stack…"
supabase start 2>&1 | tail -3
ok "Supabase running"

# ── 4. Get connection info from supabase status ───────────────────────────
info "Reading connection info from supabase status…"
STATUS_OUT=$(supabase status 2>&1)

extract() {
  echo "$STATUS_OUT" | grep -i "$1" | awk '{print $NF}' | head -1
}

SUPABASE_URL=$(extract "API URL")
ANON_KEY=$(extract "anon key")
SERVICE_KEY=$(extract "service_role key")
JWT_SECRET=$(extract "JWT secret")

if [[ -z "$SUPABASE_URL" || -z "$ANON_KEY" ]]; then
  echo "$STATUS_OUT"
  fatal "Could not parse supabase status output. Check above."
fi

ok "Got connection info"

# ── 5. Write .env.local ───────────────────────────────────────────────────
ENV_FILE="$ROOT/.env.local"

if [[ -f "$ENV_FILE" ]]; then
  warn ".env.local already exists — backing up to .env.local.bak"
  cp "$ENV_FILE" "$ENV_FILE.bak"
fi

cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev-setup.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
SUPABASE_JWT_SECRET=${JWT_SECRET}

# Dev mode — bypass Slugger postMessage auth
NEXT_PUBLIC_DEV_MODE=true
NEXT_PUBLIC_DEV_USER_ROLE=league
NEXT_PUBLIC_DEV_USER_TEAM=1
NEXT_PUBLIC_DEV_USER_ID=1
EOF

ok ".env.local written"

# ── 6. Apply migrations and seed ─────────────────────────────────────────
info "Running supabase db reset (applies migrations + seed)…"
supabase db reset --no-confirm 2>&1 | tail -5
ok "Database seeded"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup complete!"
echo ""
echo "  Start the app:  npm run dev"
echo "  Dev harness:    open scripts/dev-harness.html in a browser"
echo "  Studio:         $(extract "Studio URL")"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
